t{       0       1 / ->       0       }t
t{       1       1 / ->       1       }t
t{       2       1 / ->       2       }t
t{      -1       1 / ->      -1       }t
t{      -2       1 / ->      -2       }t
t{       0      -1 / ->       0       }t
t{       1      -1 / ->      -1       }t
t{       2      -1 / ->      -2       }t
t{      -1      -1 / ->       1       }t
t{      -2      -1 / ->       2       }t
t{       2       2 / ->       1       }t
t{      -1      -1 / ->       1       }t
t{      -2      -2 / ->       1       }t
t{       7       3 / ->       2       }t
t{       7      -3 / ->      -3       }t
t{      -7       3 / ->      -3       }t
t{      -7      -3 / ->       2       }t
t{ max-int       1 / -> max-int       }t
t{ min-int       1 / -> min-int       }t
t{ max-int max-int / ->       1       }t
t{ min-int min-int / ->       1       }t
