extern void init_evaluator(cell *evaluator,
                           cell buffer_count,
                           cell buffer_size,
                           cell evaluator_size,
                           cell fiber_count,
                           cell fiber_stack_size,
                           cell pad_buffer_size,
                           cell parameter_stack_size,
                           cell return_stack_size,
                           cell source_size,
                           cell task_count,
                           cell word_buffer_size);
