init_evaluator(
    e,
    buffer_count,
    buffer_size,
    evaluator_size,
    fiber_count,
    fiber_stack_size,
    pad_buffer_size,
    parameter_stack_size,
    return_stack_size,
    source_size,
    task_count,
    word_buffer_size);
