(  ---------------------------------------------------------  )
(                                                             )
(              Forthkit FORTH-79 Test Suite                   )
(                                                             )
(                                                             )
(  This file is based on the work of many other people, to    )
(  which I am adding a small contribution. If you find this   )
(  useful and make changes, please also share it with the     )
(  world at large[1].                                         )
(                                                             )
(  In particular, this uses a simplification of the standard  )
(  test harness[2], parts of John Hayes'[3] and Gerry         )
(  Jackson's[4] test suites, including innumerable details    )
(  from The Forth Standard website[5], which credits David    )
(  Williams and the members of the Forth 200x committee[6].   )
(                                                             )
(  [1] https://www.gnu.org/licenses/gpl-3.0.en.html           )
(  [2] http://www.forth200x.org/tests/ttester.fs              )
(  [3] https://www.taygeta.com/forth.html                     )
(  [4] http://soton.mpeforth.com/flag/anstests/index.html     )
(  [5] https://forth-standard.org                             )
(  [6] https://forth-standard.org/standard/testsuite          )
(                                                             )
(  This file is formatted into screens of 16 line groups,     )
(  each 64 characters long. Each is a "block" in terms of the )
(  FORTH-79 standard. The first three blocks -- 0, 1 and 2 -- )
(  contain introductory comments. The following blocks hold   )
(  a few definitions not present in FORTH-79, the test        )
(  harness, and then the remaining blocks contain the tests   )
(  themselves. To run the test suite, start f79 with this     )
(  file as the mass storage and then execute                  )
(                                                             )
(     8 load run-all-tests                                    )
(                                                             )
(  To run just a part of the test suite, first load block 4,  )
(  then find the relevant block in the block contents below   )
(  and load that. Loading a test suite block will run the     )
(  tests in the block.                                        )
(                                                             )
(  Block Contents:                                            )
(    0-3 Title, credits, license, contents                    )
(    4   cell cells <> -->                                    )
(    5   start-depth actual-depth actual-results              )
(    6   t{ ->                                                )
(    7   check-results                                        )
(    8   }t                                                   )
(    9   1st 2nd                                              )
(   10   run-all-tests                                        )
(   11   harness tests                                        )
(   12   and not                                              )
(   13   comments tick                                        )
(   14   *                                                    )
(   15   +                                                    )
(   16   here , ! @                                           )
(   17   +!                                                   )
(   18   +loop                                                )
(   19   +loop [continued]                                    )
(   20   +loop [continued]                                    )
(   21   +loop [continued]                                    )
(   22   -                                                    )
(   23                                                        )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(  ---------------------------------------------------------  )
(  Supplemental Words                                         )
(                                                             )
(  FORTH-79 doesn't have the words "cell" or "cells", since   )
(  since the cell size was defined to be 16 bits. Forthkit    )
(  supports compiling f79 with 16, 32, or 64 bit words.       )
                                                            ( )
here 0 , here - dup allot negate constant cell              ( )
                                                            ( )
: cell+ cell + ;                                            ( )
: cells cell * ;                                            ( )
: char+ 1+ ;                                                ( )
: chars ;                                                   ( )
: <> = 0= ;                                                 ( )
: --> blk @ 1+ load ;                                       ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Test Harness Variables                                     )
(                                                             )
(  The test harness captures the depth of the stack before    )
(  the test is run. After the subject code is executed, the   )
(  depth of the stack is checked against this and any new     )
( values are saved for comparison during verification.        )
                                                            ( )
variable start-depth                                        ( )
variable actual-depth                                       ( )
                                                            ( )
create actual-results 32 cells allot                        ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Test Harness Part 1                                        )
(                                                             )
: t{ depth start-depth ! ;                                  ( )
                                                            ( )
: ->                                                        ( )
    depth dup actual-depth !                                ( )
    start-depth @ >                                         ( )
    if                                                      ( )
        depth start-depth @ - 0                             ( )
        do                                                  ( )
            actual-results i cells + !                      ( )
        loop                                                ( )
    then                                                    ( )
;                                                           ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Test Harness Part 2                                        )
(                                                           ( )
: check-results                                             ( )
    depth start-depth @ >                                   ( )
    if                                                      ( )
        depth start-depth @ - 0                             ( )
        do                                                  ( )
            actual-results i cells + @ <>                   ( )
            if                                              ( )
                ." incorrect result"                        ( )
                leave                                       ( )
            then                                            ( )
        loop                                                ( )
    then                                                    ( )
;                                                    -->    ( )
(  ---------------------------------------------------------  )
(  Test Harness Part 3                                        )
(                                                           ( )
: }t                                                        ( )
    depth actual-depth @ =                                  ( )
    if                                                      ( )
        check-results 46 emit                               ( )
    else                                                    ( )
        ." wrong number of results."                        ( )
    then                                                    ( )
;                                                           ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Fixtures                                                   )
                                                            ( )
0      0= constant <true>                                   ( )
<true> 0= constant <false>                                  ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Comparator Tests                                           )
                                                            ( )
: run-comparator-tests                                      ( )
    ." Comparators: " cr                                    ( )
                                                            ( )
    decimal                                                 ( )
    22 load ( =                 ) 23 load ( <                 )
    24 load ( >                 ) 25 load ( 0=                )
    26 load ( 0<                ) 27 load ( 0>                )
                                                            ( )
                                                            ( )
                                                            ( )
    cr                                                      ( )
;                                                           ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Logic Tests                                                )
                                                            ( )
: run-logic-tests                                           ( )
    ." Logical Operators: " cr                              ( )
                                                            ( )
    decimal                                                 ( )
    28 load ( and not           ) 29 load ( or                )
    30 load ( xor               )                           ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
    cr                                                      ( )
;                                                           ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Arithmetic Tests                                           )
                                                            ( )
: run-arithmetic-tests                                      ( )
    ." Arithmetic Operators: " cr                           ( )
                                                            ( )
    decimal                                                 ( )
    31 load ( +                 ) 32 load ( -                 )
    33 load ( *                 ) 34 load ( /                 )
    36 load ( */                ) 38 load ( /mod              )
    40 load ( 1+ 1-             ) 41 load ( 2+ 2-             )
    42 load ( abs               ) 43 load ( max               )
    44 load ( min               )                           ( )
    cr                                                      ( )
;                                                           ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Memory Access Tests                                        )
                                                            ( )
: run-memory-access-tests                                   ( )
    ." Memory Access: " cr                                  ( )
                                                            ( )
    decimal                                                 ( )
    45 load ( here , ! @        ) 47 load ( +!                )
    48 load ( c, c! c@          ) 50 load ( cmove             )
    51 load ( fill              ) 52 load ( move              )
                                                            ( )
                                                            ( )
                                                            ( )
     cr                                                     ( )
;                                                           ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Stack Manipulation Tests                                   )
                                                            ( )
: run-stack-word-tests                                      ( )
    ." Stack Words: " cr                                    ( )
                                                            ( )
    decimal                                                 ( )
    53 load ( drop              ) 54 load ( dup               )
    55 load ( over              ) 56 load ( pick              )
    57 load ( roll              ) 58 load ( rot               )
    59 load ( swap              )                           ( )
                                                            ( )
                                                            ( )
     cr                                                     ( )
;                                                           ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Suite Control Functions                                    )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Suite Control Functions                                    )
                                                            ( )
: run-all-tests                                             ( )
    decimal 21 load             ( run test harness tests      )
    run-comparator-tests                                    ( )
    run-logic-tests                                         ( )
    run-arithmetic-tests                                    ( )
    run-memory-access-tests                                 ( )
    run-stack-word-tests                                    ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
  cr                                                        ( )
;                                                           ( )
(  ---------------------------------------------------------  )
(  Harness Tests                                              )
                                                            ( )
." Testing the test harness: "                           cr ( )
." The next line should say 'incorrect result'"          cr ( )
t{ 1 2 swap -> 1 2 }t                                 cr cr ( )
                                                            ( )
." The next line should say 'wrong number of results.'"  cr ( )
t{ 1 2 swap -> 1 2 1 }t                               cr cr ( )
                                                            ( )
." The next line should just be a period."               cr ( )
t{ 1 2 swap -> 2 1 }t                                 cr cr ( )
                                                            ( )
." Test harness tests complete. "                     cr cr ( )
                                                            ( )
                                                            ( )
(  ---------------------------------------------------------  )
(  Core Tests: =                                              )
                                                            ( )
." = "                                                      ( )
                                                            ( )
t{  0  0 = -> <true>  }t                                    ( )
t{  1  1 = -> <true>  }t                                    ( )
t{ -1 -1 = -> <true>  }t                                    ( )
t{  1  0 = -> <false> }t                                    ( )
t{ -1  0 = -> <false> }t                                    ( )
t{  0  1 = -> <false> }t                                    ( )
t{  0 -1 = -> <false> }t                                    ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: <                                              )
                                                            ( )
." < "                                                      ( )
                                                            ( )
t{       0       1 < -> <true>  }t                          ( )
t{       1       2 < -> <true>  }t                          ( )
t{      -1       0 < -> <true>  }t                          ( )
t{      -1       1 < -> <true>  }t                          ( )
t{       0       0 < -> <false> }t                          ( )
t{       1       1 < -> <false> }t                          ( )
t{       1       0 < -> <false> }t                          ( )
t{       2       1 < -> <false> }t                          ( )
t{       0      -1 < -> <false> }t                          ( )
t{       1      -1 < -> <false> }t                          ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: >                                              )
                                                            ( )
." > "                                                      ( )
                                                            ( )
t{       0       1 > -> <false> }t                          ( )
t{       1       2 > -> <false> }t                          ( )
t{      -1       0 > -> <false> }t                          ( )
t{      -1       1 > -> <false> }t                          ( )
t{       0       0 > -> <false> }t                          ( )
t{       1       1 > -> <false> }t                          ( )
t{       1       0 > -> <true>  }t                          ( )
t{       2       1 > -> <true>  }t                          ( )
t{       0      -1 > -> <true>  }t                          ( )
t{       1      -1 > -> <true>  }t                          ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: 0=                                             )
                                                            ( )
." 0= "                                                     ( )
                                                            ( )
    t{       0 0= -> <true>  }t                             ( )
    t{       1 0= -> <false> }t                             ( )
    t{       2 0= -> <false> }t                             ( )
    t{      -1 0= -> <false> }t                             ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: 0<                                             )
                                                            ( )
." 0< "                                                     ( )
                                                            ( )
    t{       0 0< -> <false> }t                             ( )
    t{      -1 0< -> <true>  }t                             ( )
    t{       1 0< -> <false> }t                             ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: 0>                                             )
                                                            ( )
." 0> "                                                     ( )
                                                            ( )
    t{       0 0> -> <false> }t                             ( )
    t{      -1 0> -> <false> }t                             ( )
    t{       1 0> -> <true>  }t                             ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: and not                                        )
                                                            ( )
." and not "                                                ( )
                                                            ( )
t{ 0 0 and -> 0 }t                                          ( )
t{ 0 1 and -> 0 }t                                          ( )
t{ 1 0 and -> 0 }t                                          ( )
t{ 1 1 and -> 1 }t                                          ( )
t{ 0 not 1 and -> 1 }t                                      ( )
t{ 1 not 1 and -> 0 }t                                      ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: or                                             )
                                                            ( )
." or "                                                     ( )
                                                            ( )
t{ 0 0 or -> 0 }t                                           ( )
t{ 0 1 or -> 1 }t                                           ( )
t{ 1 0 or -> 1 }t                                           ( )
t{ 1 1 or -> 1 }t                                           ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: xor                                            )
                                                            ( )
." xor "                                                    ( )
                                                            ( )
t{ 0 0 xor -> 0 }t                                          ( )
t{ 0 1 xor -> 1 }t                                          ( )
t{ 1 0 xor -> 1 }t                                          ( )
t{ 1 1 xor -> 0 }t                                          ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: +                                              )
                                                            ( )
." + "                                                      ( )
                                                            ( )
t{  0  5 + ->  5 }t                                         ( )
t{  5  0 + ->  5 }t                                         ( )
t{  0 -5 + -> -5 }t                                         ( )
t{ -5  0 + -> -5 }t                                         ( )
t{  1  2 + ->  3 }t                                         ( )
t{  1 -2 + -> -1 }t                                         ( )
t{ -1  2 + ->  1 }t                                         ( )
t{ -1 -2 + -> -3 }t                                         ( )
t{ -1  1 + ->  0 }t                                         ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: -                                              )
                                                            ( )
." - "                                                      ( )
                                                            ( )
t{          0  5 - ->       -5 }t                           ( )
t{          5  0 - ->        5 }t                           ( )
t{          0 -5 - ->        5 }t                           ( )
t{         -5  0 - ->       -5 }t                           ( )
t{          1  2 - ->       -1 }t                           ( )
t{          1 -2 - ->        3 }t                           ( )
t{         -1  2 - ->       -3 }t                           ( )
t{         -1 -2 - ->        1 }t                           ( )
t{          0  1 - ->       -1 }t                           ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: *                                              )
                                                            ( )
." * "                                                      ( )
                                                            ( )
t{  0  0 * ->  0 }t                                         ( )
t{  0  1 * ->  0 }t                                         ( )
t{  1  0 * ->  0 }t                                         ( )
t{  1  2 * ->  2 }t                                         ( )
t{  2  1 * ->  2 }t                                         ( )
t{  3  3 * ->  9 }t                                         ( )
t{ -3  3 * -> -9 }t                                         ( )
t{  3 -3 * -> -9 }t                                         ( )
t{ -3 -3 * ->  9 }t                                         ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: /                                              )
                                                            ( )
." / "                                                      ( )
                                                            ( )
    t{       0       1 / ->       0       }t                ( )
    t{       1       1 / ->       1       }t                ( )
    t{       2       1 / ->       2       }t                ( )
    t{      -1       1 / ->      -1       }t                ( )
    t{      -2       1 / ->      -2       }t                ( )
    t{       0      -1 / ->       0       }t                ( )
    t{       1      -1 / ->      -1       }t                ( )
    t{       2      -1 / ->      -2       }t                ( )
    t{      -1      -1 / ->       1       }t                ( )
    t{      -2      -1 / ->       2       }t                ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Core Tests: / [continued]                                  )
                                                            ( )
    t{       2       2 / ->       1      }t                 ( )
    t{      -1      -1 / ->       1      }t                 ( )
    t{      -2      -2 / ->       1      }t                 ( )
    t{       7       3 / ->       2      }t                 ( )
    t{       7      -3 / ->      -2      }t                 ( )
    t{      -7       3 / ->      -2      }t                 ( )
    t{      -7      -3 / ->       2      }t                 ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: */                                             )
                                                            ( )
." */ todo "                                                 ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Core Tests: */ [continued]                                 )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: /mod                                           )
                                                            ( )
." /mod todo "                                              ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Core Tests: /mod [continued]                               )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: 1+ 1-                                          )
                                                            ( )
." 1+ "                                                     ( )
                                                            ( )
    t{        0 1+ ->          1 }t                         ( )
    t{       -1 1+ ->          0 }t                         ( )
    t{        1 1+ ->          2 }t                    cr   ( )
                                                            ( )
." 1- "                                                     ( )
                                                            ( )
    t{        2 1- ->          1 }t                         ( )
    t{        1 1- ->          0 }t                         ( )
    t{        0 1- ->         -1 }t                         ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: 2+ 2-                                          )
                                                            ( )
." 2+ "                                                     ( )
                                                            ( )
    t{        0 2+ ->          2 }t                         ( )
    t{       -1 2+ ->          1 }t                         ( )
    t{        1 2+ ->          3 }t                    cr   ( )
                                                            ( )
." 2- "                                                     ( )
                                                            ( )
    t{        2 2- ->          0 }t                         ( )
    t{        1 2- ->         -1 }t                         ( )
    t{        0 2- ->         -2 }t                         ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: abs                                            )
                                                            ( )
." abs "                                                    ( )
                                                            ( )
t{       0 abs ->          0 }t                             ( )
t{       1 abs ->          1 }t                             ( )
t{      -1 abs ->          1 }t                             ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: max                                            )
                                                            ( )
." max "                                                    ( )
                                                            ( )
t{       0       1 max ->       1 }t                        ( )
t{       1       2 max ->       2 }t                        ( )
t{      -1       0 max ->       0 }t                        ( )
t{      -1       1 max ->       1 }t                        ( )
t{       0       0 max ->       0 }t                        ( )
t{       1       1 max ->       1 }t                        ( )
t{       1       0 max ->       1 }t                        ( )
t{       2       1 max ->       2 }t                        ( )
t{       0      -1 max ->       0 }t                        ( )
t{       1      -1 max ->       1 }t                        ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: min                                            )
                                                            ( )
." min "                                                    ( )
                                                            ( )
t{       0       1 min ->       0 }t                        ( )
t{       1       2 min ->       1 }t                        ( )
t{      -1       0 min ->      -1 }t                        ( )
t{      -1       1 min ->      -1 }t                        ( )
t{       0       0 min ->       0 }t                        ( )
t{       1       1 min ->       1 }t                        ( )
t{       1       0 min ->       0 }t                        ( )
t{       2       1 min ->       1 }t                        ( )
t{       0      -1 min ->      -1 }t                        ( )
t{       1      -1 min ->      -1 }t                        ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: here , ! @                                     )
                                                            ( )
." here , ! @ "                                             ( )
                                                            ( )
here 1 ,                                                    ( )
here 2 ,                                                    ( )
constant 2nd                                                ( )
constant 1st                                                ( )
                                                            ( )
t{       1st 2nd <  -> 1 2 < }t  ( todo u<                    )
t{       1st cell+  -> 2nd   }t                             ( )
t{   1st 1 cells +  -> 2nd   }t                             ( )
t{     1st @ 2nd @  -> 1 2   }t                             ( )
                                                            ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Core Tests: here , ! @ [continued]                         )
                                                            ( )
t{         5 1st !  ->       }t                             ( )
t{     1st @ 2nd @  -> 5 2   }t                             ( )
t{         6 2nd !  ->       }t                             ( )
t{     1st @ 2nd @  -> 5 6   }t                             ( )
t{ 1   1st ! 1st @  -> 1     }t  ( can store cell-wide value  )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: +!                                             )
                                                            ( )
." +! "                                                     ( )
                                                            ( )
here 1 ,                                                    ( )
here 2 ,                                                    ( )
constant 2nd                                                ( )
constant 1st                                                ( )
                                                            ( )
t{  0 1st !        ->   }t                                  ( )
t{  1 1st +!       ->   }t                                  ( )
t{    1st @        -> 1 }t                                  ( )
t{ -1 1st +! 1st @ -> 0 }t                                  ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: c, c! c@                                       )
                                                            ( )
." c, c! c@ "                                               ( )
                                                            ( )
here 1 c,                                                   ( )
here 2 c,                                                   ( )
constant 2ndc                                               ( )
constant 1stc                                               ( )
                                                            ( )
t{    1stc 2ndc <  -> <true> }t                ( todo u<      )
t{ 1stc 1+         ->  2ndc  }t                             ( )
t{ 1stc c@ 2ndc c@ ->   1 2  }t                             ( )
t{       3 1stc c! ->        }t                             ( )
                                                            ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Core Tests: c, c! c@ [continued]                           )
                                                            ( )
t{ 1stc c@ 2ndc c@ ->   3 2  }t                             ( )
t{       4 2ndc c! ->        }t                             ( )
t{ 1stc c@ 2ndc c@ ->   3 4  }t                             ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: cmove                                          )
                                                            ( )
." cmove "                                                  ( )
                                                            ( )
create fbuf 20 c, 20 c, 20 c,                               ( )
create sbuf 12 c, 34 c, 56 c,                               ( )
: seebuf fbuf c@ fbuf char+ c@ fbuf char+ char+ c@ ;        ( )
                                                            ( )
t{ fbuf fbuf 3 chars cmove seebuf -> 20 20 20 }t            ( )
t{ sbuf fbuf 0 chars cmove seebuf -> 20 20 20 }t            ( )
t{ sbuf fbuf 1 chars cmove seebuf -> 12 20 20 }t            ( )
t{ sbuf fbuf 3 chars cmove seebuf -> 12 34 56 }t            ( )
t{ fbuf char+ fbuf 2 chars cmove seebuf -> 34 56 56 }t      ( )
t{ fbuf fbuf char+ 2 chars cmove seebuf -> 34 34 34 }t      ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: fill                                           )
                                                            ( )
." fill "                                                   ( )
                                                            ( )
create fbuf 00 c, 00 c, 00 c,                               ( )
: seebuf fbuf c@ fbuf char+ c@ fbuf char+ char+ c@ ;        ( )
                                                            ( )
t{ fbuf 0 20 fill seebuf -> 00 00 00 }t                     ( )
t{ fbuf 1 20 fill seebuf -> 20 00 00 }t                     ( )
t{ fbuf 3 20 fill seebuf -> 20 20 20 }t                     ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests:  move                                          )
                                                            ( )
." move "                                                   ( )
                                                            ( )
create wbuf 20 , 20 , 20 ,                                  ( )
create rbuf 12 , 34 , 56 ,                                  ( )
: seebuf wbuf @ wbuf cell+ @ wbuf cell+ cell+ @ ;           ( )
                                                            ( )
t{ wbuf wbuf 3 move seebuf -> 20 20 20 }t                   ( )
t{ rbuf wbuf 0 move seebuf -> 20 20 20 }t                   ( )
t{ rbuf wbuf 1 move seebuf -> 12 20 20 }t                   ( )
t{ rbuf wbuf 3 move seebuf -> 12 34 56 }t                   ( )
t{ wbuf cell+ wbuf 2 move seebuf -> 34 56 56 }t             ( )
t{ wbuf wbuf cell+ 2 move seebuf -> 34 34 34 }t             ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: drop                                           )
                                                            ( )
." drop "                                                   ( )
                                                            ( )
t{ 1 2 drop -> 1 }t                                         ( )
t{ 0   drop ->   }t                                         ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: dup                                            )
                                                            ( )
." dup "                                                    ( )
                                                            ( )
t{ 1 dup -> 1 1 }t                                          ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: over                                           )
                                                            ( )
." over "                                                   ( )
                                                            ( )
t{ 1 2 over -> 1 2 1 }t                                     ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: pick                                           )
                                                            ( )
." pick "                                                   ( )
                                                            ( )
t{ 3 1 pick -> 3 3 }t                                       ( )
t{ 4 1 2 pick -> 4 1 4 }t                                   ( )
t{ 5 4 3 2 1 5 pick -> 5 4 3 2 1 5 }t                       ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: roll                                           )
                                                            ( )
." roll "                                                   ( )
                                                            ( )
t{ 1 roll -> }t                                             ( )
t{ 3 4 2 roll -> 4 3 }t                                     ( )
t{ 4 5 6 3 roll -> 5 6 4 }t                                 ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: rot                                            )
                                                            ( )
." rot "                                                    ( )
                                                            ( )
t{ 1 2 3 rot -> 2 3 1 }t                                    ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: swap                                           )
                                                            ( )
." swap "                                                   ( )
                                                            ( )
t{ 1 2 swap -> 2 1 }t                                       ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: comments tick                                  )
                                                            ( )
." comments "                                               ( )
                                                            ( )
t{ ( a comment)1234 -> 1234 }t                              ( )
t{ : pc1 ( a comment)1234 ; pc1 -> 1234 }t                  ( )
                                                            ( )
cr                                                          ( )
                                                            ( )
." tick "                                                   ( )
                                                            ( )
( t{ : gt1 123 ;   ->     }t                                ( )
( t{ ' gt1 execute -> 123 }t                                ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: comments tick                                  )
                                                            ( )
." comments "                                               ( )
                                                            ( )
t{ ( a comment)1234 -> 1234 }t                              ( )
t{ : pc1 ( a comment)1234 ; pc1 -> 1234 }t                  ( )
                                                            ( )
cr                                                          ( )
                                                            ( )
." tick "                                                   ( )
                                                            ( )
( t{ : gt1 123 ;   ->     }t                                ( )
( t{ ' gt1 execute -> 123 }t                                ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: +loop                                          )
                                                            ( )
." +loop "                                                  ( )
                                                            ( )
t{ : gd2 do i -1 +loop ; -> }t                              ( )
t{  1 4 gd2 -> 4 3 2  1 }t                                  ( )
t{ -1 2 gd2 -> 2 1 0 -1 }t                                  ( )
                                                            ( )
( There is a subtle difference in the definition of +loop     )
( between FORTH-79 and FORTH-83. The earlier version defines  )
( loop exit as the index being >= the limit -- if inc > 0 --  )
( and < the limit if inc < 0. All later versions define the   )
( exit condition in terms of the index crossing the limit.    )
( 8 of the test cases below were changed for FORTH-79.        )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Core Tests: +loop [continued]                              )
                                                            ( )
variable gditerations                                       ( )
variable gdincrement                                        ( )
                                                            ( )
: gd7 ( limit start increment -- )                          ( )
    gdincrement !                                           ( )
    0 gditerations !                                        ( )
    do                                                      ( )
        1 gditerations +!                                   ( )
        i                                                   ( )
        gditerations @ 6 = if leave then                    ( )
        gdincrement @                                       ( )
    +loop gditerations @                                    ( )
;                                                    -->    ( )
(  ---------------------------------------------------------  )
(  Core Tests: +loop [continued]                              )
                                                            ( )
t{    4  4  -1 gd7 ->  4                  1  }t             ( )
t{    1  4  -1 gd7 ->  4  3  2  1         4  }t             ( )
t{    4  1  -1 gd7 ->  1                  1  }t             ( )
t{    4  1   0 gd7 ->  1  1  1  1   1   1 6  }t             ( )
t{    0  0   0 gd7 ->  0                  1  }t             ( )
t{    1  4   0 gd7 ->  4                  1  }t             ( )
t{    1  4   1 gd7 ->  4                  1  }t             ( )
t{    4  1   1 gd7 ->  1  2  3            3  }t             ( )
t{    4  4   1 gd7 ->  4                  1  }t             ( )
t{    2 -1  -1 gd7 -> -1                  1  }t             ( )
t{   -1  2  -1 gd7 ->  2  1  0 -1         4  }t             ( )
t{    2 -1   0 gd7 -> -1 -1 -1 -1  -1  -1 6  }t             ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Core Tests: +loop [continued]                              )
                                                            ( )
t{   -1  2   0 gd7 ->  2                  1  }t             ( )
t{   -1  2   1 gd7 ->  2                  1  }t             ( )
t{    2 -1   1 gd7 -> -1 0 1              3  }t             ( )
t{  -20 30 -10 gd7 -> 30 20 10  0 -10 -20 6  }t             ( )
t{  -20 31 -10 gd7 -> 31 21 11  1  -9 -19 6  }t             ( )
t{  -20 29 -10 gd7 -> 29 19  9 -1 -11     5  }t             ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
(  Core Tests: ." : ;                                         )
                                                            ( )
." <dot quote> "                                            ( )
                                                            ( )
t{ : pb1 ." you should see 2345: "." 2345"; pb1 -> }t       ( )
                                                            ( )
cr                                                          ( )
                                                            ( )
." : ; "                                                    ( )
                                                            ( )
t{ : gdx   123 ;    : gdx   gdx 234 ; -> }t                 ( )
t{ gdx -> 123 234 }t                                        ( )
                                                            ( )
                                                            ( )
cr                                                          ( )
(  ---------------------------------------------------------  )
