(  ---------------------------------------------------------  )
(                                                             )
(              Forthkit FORTH-79 Test Suite                   )
(                                                             )
(                                                             )
(  This file is based on the work of many other people, to    )
(  which I am adding a small contribution. If you find this   )
(  useful and make changes, please also share it with the     )
(  world at large[1].                                         )
(                                                             )
(  In particular, this uses a simplification of the standard  )
(  test harness[2], parts of John Hayes'[3] and Gerry         )
(  Jackson's[4] test suites, innumerable details from The     )
(  Forth Standard website[5], which also credits David        )
(  Williams and the members of the Forth 200x committee[6].   )
(                                                             )
(  [1] https://www.gnu.org/licenses/gpl-3.0.en.html           )
(  [2] http://www.forth200x.org/tests/ttester.fs              )
(  [3] https://www.taygeta.com/forth.html                     )
(  [4] http://soton.mpeforth.com/flag/anstests/index.html     )
(  [5] https://forth-standard.org                             )
(  [6] https://forth-standard.org/standard/testsuite          )
(                                                             )
(  This file is formatted into screens of 16 line groups,     )
(  each 64 characters long. Each is a "block" in terms of the )
(  FORTH-79 standard. The first three blocks -- 0, 1 and 2 -- )
(  contain introductory comments. The following blocks hold   )
(  a few definitions not present in FORTH-79, the test        )
(  harness, and then the remaining blocks contain the tests   )
(  themselves. To run the test suite, start f79 with this     )
(  file as the mass storage and then execute                  )
(                                                             )
(     4 load run-all-tests                                    )
(                                                             )
(  To run just a part of the test suite, first load block 4,  )
(  then find the relevant block in the block contents below   )
(  and load that. Loading a test suite block will run the     )
(  tests in the block.                                        )
(                                                             )
(  Block Contents:                                            )
(    0-3 Title, credits, license, contents                    )
(    4   cell cells <> -->                                    )
(    5   start-depth actual-depth actual-results              )
(    6   t{ ->                                                )
(    7   check-results                                        )
(    8   }t                                                   )
(    9   run-all-tests                                        )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(                                                             )
(  ---------------------------------------------------------  )
(  Supplemental Words                                         )
(                                                             )
(  FORTH-79 doesn't have the words "cell" or "cells", since   )
(  since the cell size was defined to be 16 bits. Forthkit    )
(  supports compiling f79 with 16, 32, or 64 bit words.       )
                                                            ( )
here 0 , here - dup allot negate                            ( )
constant cell                                               ( )
                                                            ( )
: cells cell * ;                                            ( )
                                                            ( )
: <> = 0= ;                                                 ( )
                                                            ( )
: --> blk @ 1+ load ;                                       ( )
                                                        --> ( )
(  ---------------------------------------------------------  )
(  Test Harness Variables                                     )
(                                                             )
(  The test harness captures the depth of the stack before    )
(  the test is run. After the subject code is executed, the   )
(  depth of the stack is checked against this and any new     )
( values are saved for comparison during verification.        )
                                                            ( )
variable start-depth                                        ( )
                                                            ( )
variable actual-depth                                       ( )
                                                            ( )
create actual-results 32 cells allot                        ( )
                                                            ( )
                                                            ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Test Harness Part 1                                        )
(                                                             )
: t{ depth start-depth ! ;                                  ( )
                                                            ( )
: ->                                                        ( )
    depth dup actual-depth !                                ( )
    start-depth @ >                                         ( )
    if                                                      ( )
        depth start-depth @ - 0                             ( )
        do                                                  ( )
            actual-results i cells + !                      ( )
        loop                                                ( )
    then ;                                                  ( )
                                                            ( )
                                                     -->    ( )
(  ---------------------------------------------------------  )
(  Test Harness Part 2                                        )
(                                                           ( )
: check-results                                             ( )
    depth start-depth @ >                                   ( )
    if                                                      ( )
        depth start-depth @ - 0                             ( )
        do                                                  ( )
            actual-results i cells + @ <>                   ( )
            if                                              ( )
                ." incorrect result: "                      ( )
                leave                                       ( )
            then                                            ( )
        loop                                                ( )
    then                                                    ( )
;                                                    -->    ( )
(  ---------------------------------------------------------  )
(  Test Harness Part 3                                        )
(                                                           ( )
: }t                                                        ( )
    depth actual-depth @ =                                  ( )
    if                                                      ( )
        check-results                                       ( )
    else                                                    ( )
        ." wrong number of results: "                       ( )
    then                                                    ( )
;                                                           ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
                                                            ( )
(  ---------------------------------------------------------  )
(  Test Harness Part 3                                        )
