#! /usr/bin/env python3

if __name__ == '__main__':
    import re
    import sys
    from pprint import pprint

    symbols = {}
    for line in sys.stdin.readlines():
        if line.startswith('defining ') or line.startswith('operator '):
            _, key, value = re.split(' +', line.strip())
            symbols[key] = value
        else:
            for key, value in symbols.items():
                try:
                    line = re.sub(re.escape(value).rjust(8, ' '), key.rjust(8, ' '), line)
                except:
                    print(key, value, line)
                    raise
            print(line, end='')

    #pprint(symbols)
